In [100]:
import pandas as pd
import numpy as np
import math as math

In [12]:
home_data=pd.read_csv('/home/fractaluser/Desktop/Untitled Folder 2/ml_splzn_coursera/regression/week2/home_data.csv')
home_train=pd.read_csv('/home/fractaluser/Desktop/Untitled Folder 2/ml_splzn_coursera/regression/week2/kc_house_train_data.csv')
home_test=pd.read_csv('/home/fractaluser/Desktop/Untitled Folder 2/ml_splzn_coursera/regression/week2/kc_house_test_data.csv')

# adding addtional columns in training set

In [20]:
home_train['bedrooms_squared']=home_train['bedrooms']*home_train['bedrooms']
home_train['bed_bath_rooms']=home_train['bedrooms']*home_train['bathrooms']
home_train['log_sqft_living']=np.log(home_train['sqft_living'])
home_train['lat_plus_long']=home_train['lat']+home_train['long']

# adding additional columns in test set

In [23]:
home_test['bedrooms_squared']=home_test['bedrooms']*home_test['bedrooms']
home_test['bed_bath_rooms']=home_test['bedrooms']*home_test['bathrooms']
home_test['log_sqft_living']=np.log(home_test['sqft_living'])
home_test['lat_plus_long']=home_test['lat']+home_test['long']

# Features for model 1,2,3

In [62]:
model_1_features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']
model_2_features = model_1_features + ['bed_bath_rooms']
model_3_features = model_2_features + ['bedrooms_squared', 'log_sqft_living', 'lat_plus_long']

# learning over model 1 features

In [162]:
X1=home_train[model_1_features]
y1=home_train['price']

In [163]:
X1.shape

(17384, 5)

In [177]:
from sklearn.linear_model import LinearRegression
model_1=LinearRegression()
model_1.fit(X1,y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

# Predicting using Model 1

In [178]:
y1_pred=model_1.predict(X1)
prices_model_1= pd.DataFrame({'Actual':y,'Predictions':y1_pred.astype(int)})
prices_model_1

Actual  Predictions
0       221900.0       244657
1       538000.0       855689
2       180000.0       318101
3       604000.0       508443
4       510000.0       420456
5      1225000.0      1581492
6       257500.0       320293
7       291850.0       166001
8       229500.0       457486
9       323000.0       325951
10      662500.0      1035689
11      468000.0       426587
12      400000.0       317028
13      530000.0       484886
14      395000.0       533393
15      485000.0       443989
16      189000.0       162709
17      230000.0       165164
18      385000.0       486225
19     2000000.0       862078
20      285000.0       340600
21      252700.0       145599
22      329000.0       544133
23      937000.0       768779
24      667000.0       404029
25      438000.0       498199
26      719000.0       726347
27      280000.0       488550
28      687500.0       702978
29      322500.0       401347
...          ...          ...
17354   610950.0       555892
17355  3567000.0      1335700
17356   362500.0       302456
17357   645000.0       569507
17358   594866.0       665648
17359   625000.0       665648
17360   380000.0       366012
17361   270000.0       304408
17362   505000.0       549280
17363   385000.0       537015
17364   414500.0       466248
17365   347500.0       510855
17366  1222500.0      1421519
17367   572000.0       694003
17368   475000.0       389130
17369   520000.0       554291
17370   679950.0       850555
17371  1575000.0       941860
17372   541800.0       672308
17373   810000.0      1143582
17374  1537000.0      1258001
17375   467000.0       485502
17376   224000.0       144626
17377   507250.0       510498
17378   429000.0       405415
17379  1007500.0      1023513
17380   475000.0       399370
17381   360000.0       528928
17382   400000.0       356549
17383   325000.0       317948

[17384 rows x 2 columns]

# Calculating Goodness of Fit Using sklearn for model 1

In [179]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y1_pred,y1)

55676481997.787949

# Learning over model 2 features

In [180]:
X2=home_train[model_2_features]
y2=home_train['price']

In [181]:
model_2=LinearRegression()
model_2.fit(X2,y2)
model_2.coef_

array([  3.06610053e+02,  -1.13446368e+05,  -7.14613083e+04,
         6.54844630e+05,  -2.94298969e+05,   2.55796520e+04])

# Predicting using Model 2

In [182]:
y2_pred=model_2.predict(X2)
prices_model_2=pd.DataFrame({'Actual':y2,'Predicted':y2_pred.astype(int)})
prices_model_2

Actual  Predicted
0       221900.0     251332
1       538000.0     839750
2       180000.0     354879
3       604000.0     510647
4       510000.0     416675
5      1225000.0    1592216
6       257500.0     310615
7       291850.0     167650
8       229500.0     459563
9       323000.0     316918
10      662500.0    1014628
11      468000.0     460453
12      400000.0     317622
13      530000.0     469508
14      395000.0     529259
15      485000.0     418136
16      189000.0     199024
17      230000.0     171374
18      385000.0     471510
19     2000000.0     840225
20      285000.0     347677
21      252700.0     165140
22      329000.0     532399
23      937000.0     758425
24      667000.0     408184
25      438000.0     493730
26      719000.0     721093
27      280000.0     503121
28      687500.0     683921
29      322500.0     403108
...          ...        ...
17354   610950.0     536993
17355  3567000.0    1409543
17356   362500.0     319884
17357   645000.0     547445
17358   594866.0     647994
17359   625000.0     647994
17360   380000.0     354485
17361   270000.0     295257
17362   505000.0     526339
17363   385000.0     524503
17364   414500.0     480630
17365   347500.0     498374
17366  1222500.0    1419077
17367   572000.0     690350
17368   475000.0     380831
17369   520000.0     540381
17370   679950.0     860288
17371  1575000.0     942056
17372   541800.0     663200
17373   810000.0    1138928
17374  1537000.0    1301943
17375   467000.0     473532
17376   224000.0     146277
17377   507250.0     500936
17378   429000.0     399222
17379  1007500.0    1024337
17380   475000.0     387127
17381   360000.0     515931
17382   400000.0     347955
17383   325000.0     361864

[17384 rows x 2 columns]

# Goodness of fit for Model 2 using sklearn

In [183]:
mean_squared_error(y2_pred,y2)

55132284576.281059

# Learning over model 3 features

In [184]:
X3=home_train[model_3_features]
y3=home_train['price']

In [185]:
model_3=LinearRegression()
model_3.fit(X3,y3)
model_3.coef_

array([  5.29422820e+02,   3.45142296e+04,   6.70607813e+04,
         5.34085611e+05,  -4.06750711e+05,  -8.57050439e+03,
        -6.78858667e+03,  -5.61831484e+05,   1.27334900e+05])

# Predicting using Model 3

In [186]:
y3_pred=model_3.predict(X3)
prices_model_3=pd.DataFrame({'Actual':y3,'Predted':y3_pred.astype(int)})
prices_model_3

Actual  Predted
0       221900.0   283863
1       538000.0   790213
2       180000.0   457872
3       604000.0   500054
4       510000.0   402051
5      1225000.0  1790635
6       257500.0   295006
7       291850.0   250201
8       229500.0   393630
9       323000.0   299521
10      662500.0  1013416
11      468000.0   418920
12      400000.0   339484
13      530000.0   487833
14      395000.0   497215
15      485000.0   439197
16      189000.0   146070
17      230000.0   185231
18      385000.0   491767
19     2000000.0   819502
20      285000.0   326243
21      252700.0   183699
22      329000.0   482894
23      937000.0   689828
24      667000.0   393565
25      438000.0   487327
26      719000.0   698659
27      280000.0   488316
28      687500.0   657647
29      322500.0   389258
...          ...      ...
17354   610950.0   554225
17355  3567000.0  1474605
17356   362500.0   381907
17357   645000.0   567887
17358   594866.0   633284
17359   625000.0   633284
17360   380000.0   420539
17361   270000.0   278797
17362   505000.0   531281
17363   385000.0   545333
17364   414500.0   460309
17365   347500.0   459716
17366  1222500.0  1556514
17367   572000.0   667676
17368   475000.0   455554
17369   520000.0   512479
17370   679950.0   869636
17371  1575000.0   946721
17372   541800.0   649258
17373   810000.0  1187518
17374  1537000.0  1351258
17375   467000.0   509076
17376   224000.0   144819
17377   507250.0   468632
17378   429000.0   405767
17379  1007500.0  1032844
17380   475000.0   442185
17381   360000.0   534529
17382   400000.0   360054
17383   325000.0   343108

[17384 rows x 2 columns]

# Goodness of Fit for Model 3 using sklearn

In [187]:
mean_squared_error(y3_pred,y3)

51969423323.198288

# Computing Goodness of Fit or Rss for Test data (price)

In [188]:
y_price_test=home_test['price']

# Using Model 1 for predition on test data 


In [189]:
X1_test=home_test[model_1_features]
y_pred_model_1=model_1.predict(X1_test)

In [207]:
Prices_pred_model_1=pd.DataFrame({'Actual':y_price_test,'Predited':y_pred_model_1.astype(int)})
Prices_pred_model_1.head()

Actual  Predited
0  310000.0    475157
1  650000.0    845336
2  233000.0    277856
3  580500.0    584714
4  535000.0    370096

# Goodness of fit or RSS for Test with model 1

In [200]:
mean_squared_error(y_pred_model_1,y_price_test)

53322409504.726967

# Using Model 2 for predictions on test data

In [201]:
X2_test=home_test[model_2_features]
y_pred_model_2=model_2.predict(X2_test)

In [206]:
Prices_pred_model_2=pd.DataFrame({'Actual':y_price_test,'Predicted':y_pred_model_2.astype(int)})
Prices_pred_model_2.head()

Actual  Predicted
0  310000.0     479919
1  650000.0     842029
2  233000.0     272476
3  580500.0     572020
4  535000.0     374831

# Goodness of Fit  or RSS for Test with model 2

In [199]:
mean_squared_error(y_pred_model_2,y_price_test)

52820397960.857765

# Using Model 2 for prediction

In [204]:
X3_test=home_test[model_3_features]
y3_pred_model3=model_3.predict(X3_test)

In [205]:
Prices_pred_model_3=pd.DataFrame({'Actual':y_price_test,'Predicted':y3_pred_model3})
Prices_pred_model_3.head()

Actual      Predicted
0  310000.0  462217.937109
1  650000.0  822911.094625
2  233000.0  249965.267710
3  580500.0  535805.033127
4  535000.0  431295.275504

# Goodness of Fit or RSS using model 3

In [208]:
mean_squared_error(y3_pred_m3,y_price_test)

61299673494.249222

# Predicting value for 9th and 11th element using all 3 models

In [213]:
model_1.predict(X1_test.iloc[9])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 835716.82289065])

In [215]:
model_1.predict(X1_test.iloc[11])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 256710.34540148])

In [214]:
model_2.predict(X2_test.iloc[9])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 819166.15914937])

In [216]:
model_2.predict(X2_test.iloc[11])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 257783.87273367])

In [217]:
model_3.predict(X3_test.iloc[9])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 795272.68072008])

In [219]:
model_3.predict(X3_test.iloc[11])

/home/fractaluser/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 254587.2744851])